spring:
  application:
    name: ability-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/pragma_reto_reactivo_ability_db
    username: root
    password: admin
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc.core: DEBUG

server:
  port: 8082

springdoc:
  title: "API Capacidades"
  description: "API para la gestion de capacidades"
  version: "v1.0.0"
  contact-name: "Darwin Galindo"
  contact-email: "dargalindosilva@gmail.com"
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui