CREATE TABLE IF NOT EXISTS ability (
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(50) NOT NULL,
   description VARCHAR(90) NOT NULL
);

CREATE TABLE IF NOT EXISTS ability_technology (
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   ability_id BIGINT NOT NULL,
   technology_id BIGINT NOT NULL
);